spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student_db1
    username: root
    password: charan

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update

external:
  feature: true
  url: http://localhost:9999/send/mail/{id}

logging:
  level:
    root: DEBUG
    org:
      example:
        main: DEBUG
api:
   key: student-course-123
jwt:
  secret: my-super-secret-key-that-is-long-enough-1234567890!@#